<div class="container">
  <h3 class="text-center mt-2">PRIVACY POLICY</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima laudantium inventore, accusamus modi quis doloribus eos, incidunt distinctio numquam unde, odio iure reiciendis veniam voluptates voluptatibus maxime nulla magnam? Maxime praesentium debitis illum aut optio atque est, omnis, placeat nemo, dolore iste? Obcaecati ipsum distinctio itaque repellendus quis inventore libero dolorem laborum sequi nostrum natus, sunt, hic voluptates soluta porro ut, vero. Fugit voluptatum error omnis totam commodi dolorem perspiciatis libero aperiam mollitia voluptates officia iste eligendi fuga, esse dolore.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
  <h4>INFORMATION COLLECTED</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima laudantium inventore, accusamus modi quis doloribus eos, incidunt distinctio numquam unde, odio iure reiciendis veniam voluptates voluptatibus maxime nulla magnam? Maxime praesentium debitis illum aut optio atque est, omnis, placeat nemo, dolore iste? Obcaecati ipsum distinctio itaque repellendus quis inventore libero dolorem laborum sequi nostrum natus, sunt, hic voluptates soluta porro ut, vero. Fugit voluptatum error omnis totam commodi dolorem perspiciatis libero aperiam mollitia voluptates officia iste eligendi fuga, esse dolore.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
  <h4>USE AND DISCLOSURE OF INFORMATION</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
  <h4>ACCESS TO PERSONAL INFORMATION</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
  <h4>LINKS TO OTHER WEBSITES</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
  <h4>SECURITY</h4>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima laudantium inventore, accusamus modi quis doloribus eos, incidunt distinctio numquam unde, odio iure reiciendis veniam voluptates voluptatibus maxime nulla magnam? Maxime praesentium debitis illum aut optio atque est, omnis, placeat nemo, dolore iste? Obcaecati ipsum distinctio itaque repellendus quis inventore libero dolorem laborum sequi nostrum natus, sunt, hic voluptates soluta porro ut, vero. Fugit voluptatum error omnis totam commodi dolorem perspiciatis libero aperiam mollitia voluptates officia iste eligendi fuga, esse dolore.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci perferendis in eos deserunt quos, ullam, minima ab, hic odit placeat rem asperiores unde. Quis recusandae tempora assumenda veritatis delectus dolor, provident ipsam dignissimos impedit numquam, inventore! Doloremque excepturi in fugiat similique. Debitis perferendis laborum itaque maiores fugit eveniet quidem reiciendis optio pariatur ipsam, aliquid dolor quam est voluptate laudantium molestias odit vel dignissimos, consectetur at! Facilis quibusdam perspiciatis est omnis nam porro alias. Dolorem reiciendis repellendus obcaecati, adipisci. Sit, reprehenderit.</p>
</div>
